// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasswordManager.Data;

#nullable disable

namespace PasswordManager.Migrations
{
    [DbContext(typeof(PasswordDbContext))]
    partial class PasswordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PasswordManager.Models.AccountModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("aesIV")
                        .HasColumnType("text");

                    b.Property<string>("aesKey")
                        .HasColumnType("text");

                    b.Property<string>("insertedDateTime")
                        .HasColumnType("text");

                    b.Property<string>("lastModifiedDateTime")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("id");

                    b.ToTable("PasswordTableEF");
                });
#pragma warning restore 612, 618
        }
    }
}
